# Generated by Django 5.2.4 on 2025-08-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_pedido_estado_alter_pedido_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PedidoProducto',
            new_name='ProductoPedido',
        ),
    ]
